### ISSUE TITLE
Implement layouts

### ISSUE THREAD

**Issue by ShchAlexander** [LiquidEngine/legui#29]
Implement different layouts, which allow: 
 * create automatically resizable components.
 * create components pinned to one of edges of parent component.

1. - [x] - Implement layout interface
2. - [ ] - Implement layouts
   * - [x] - Border pane
   * - [x] - Horizontal box
   * - [x] - Vertical box
   * - [ ] - Stack box
   * - [ ] - Grid pane

**Comment by VadimGush** [comment]
1. **Border pane** - provides five regions in which to place components: top, bottom, left, right and center.
The regions can be any size.

![screenshot from 2017-11-08 16-14-54 - 1](https://user-images.githubusercontent.com/6123702/32548707-0e431cbc-c4a0-11e7-8d7f-bbee8ea455a0.png)

2. **Horizontal box** - provides single row to place components. The width of each column is the width of component inside it.

![screenshot from 2017-11-08 16-01-37](https://user-images.githubusercontent.com/6123702/32548207-5753e37a-c49e-11e7-8e87-812492e09e41.png)

3. **Vertical box**  - provides single column to place components. Works like horizontal box.
4. **Stack box** - places all of the components within a single stack with each new component added on top of previous.

![screenshot from 2017-11-08 15-56-12](https://user-images.githubusercontent.com/6123702/32548081-d6302d4e-c49d-11e7-9574-2bf4db769647.png)

5. **Grid pane**

![grid](https://user-images.githubusercontent.com/6123702/32548771-4bb908a4-c4a0-11e7-85b0-d7bf7d81eec1.png)

**Comment by ShchAlexander** [comment]
Border layout is done...
![borderlayout1](https://user-images.githubusercontent.com/6692636/33212338-a8a957ea-d133-11e7-8741-d0035304be36.gif)

**Comment by ShchAlexander** [comment]
Created PR: #61

**Comment by ShchAlexander** [comment]
Hello @VadimGush, can you please provide more information on layout behaviors?
For horizontal box - should child components stretch on height or not? 
The same for vertical box.

About grid pane - sizes of rows and columns should be defined in layout?

**Comment by ShchAlexander** [comment]
Here is another layout:
![animation](https://user-images.githubusercontent.com/6692636/35064800-469e2926-fbdc-11e7-95d0-46a87e7ced9a.gif)

**Comment by ShchAlexander** [comment]
Basically almost all these layouts could be implemented with FLEX style.
Closing the issue.
