### ISSUE TITLE
Incorrect icon on widget

### ISSUE THREAD

**Issue by VadimGush** [LiquidEngine/legui#54]
An incorrect icon displayed when the widget is closed in advance.
![image](https://user-images.githubusercontent.com/6123702/30488402-448917dc-9a47-11e7-8ae2-230bb87c502f.png)

**Comment by ShchAlexander** [comment]
Is it reproducible on examples?

**Comment by ShchAlexander** [comment]
Fixed in 1.1.10 version (https://github.com/LiquidEngine/legui/commit/2de9b32a8cf5ae7d719357db67d4a8e038678b20)
