### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by cout970** [LiquidEngine/legui#57]
The function NvgRenderer.render(Frame frame, Context context) takes a lot of cpu time, as you can see in my application it takes even more time to run that function than render all the scene:

![https://prnt.sc/h664n9](https://image.prntscr.com/image/DYjKl8PYTtGrHu23cdjUcQ.png)

Right now I get around 25-30 fps, but removing that function call I get more than 60 fps.
I'm investigating what causes that lag.
You can find the lastest version of the application at the [github repo](https://github.com/cout970/Modeler)

**Comment by cout970** [comment]
FontRegistry.getFontRegister() is only used in NvgRenderer.loadFontsToNvg() and it's iterated for every entry, this can be optimized using a LinkHashMap instead a HashMap, a LinkedHashMap stores in every entry a link to the next so the iteration is faster.

https://github.com/LiquidEngine/legui/blob/develop/src/main/java/org/liquidengine/legui/font/FontRegistry.java#L82

**Comment by cout970** [comment]
I ran the profiler and this is the result:
![http://prntscr.com/h66fir](https://image.prntscr.com/image/PqMF-2m7SmK55pvH4_k9cw.png)
getAbsolutePosition() is being used millions of times (this is normal) and it takes 5.5% of the total cpu time.
This is a posible optimization:
```
public Vector2f getAbsolutePositionOld() {
        Vector2f screenPos = new Vector2f(this.position);
        for (Component parent = this.getParent(); parent != null; parent = parent.getParent()) {
            screenPos.add(parent.getPosition());
        }
        return screenPos;
}

public Vector2f getAbsolutePositionNew() {
        float x = position.x;
        float y = position.y;
        
        for (Component parent = this.getParent(); parent != null; parent = parent.getParent()) {
            Vector2f parentPos = parent.getPosition();
            x += parentPos.x;
            y += parentPos.y;
        }
        return new Vector2f(x, y);
}
```
Why is this more efficient? if we look at the profiler result Vector2f.add(...) it's called 116 million times!, that's a hint that the JIT compiler cannot inline it.
```
public Vector2f add(Vector2fc v) {
        x += v.x();
        y += v.y();
        return this;
    }
```
The function has an interface as a paramenter so probably JIT cannot inline that as just `x+= other.x and y += other.y` if we do that manually it could go much faster.
### Disclaimer
I not an expert, so my assumptions may be wrong and any change in the code must be checked empirically to make that it really affects the application performance

**Comment by ShchAlexander** [comment]
Ok, I'll try this approach ASAP.

**Comment by ShchAlexander** [comment]
I've profiled application and found that the most long operation is in external library (NanoVG).  
It seems that it is old issue (found next one https://github.com/memononen/nanovg/issues/371)...

So for now I can't fix it but it's a good point to find (or implement) better vector graphics library.

![screenshot_100](https://user-images.githubusercontent.com/6692636/32656603-87905740-c623-11e7-9208-cb07190b53c8.png)  

![screenshot_101](https://user-images.githubusercontent.com/6692636/32656607-8a809ce4-c623-11e7-9898-e913b018eb17.png)

**Comment by cout970** [comment]
Holy F**k, I made a workaround for #72 and I went from 30-40fpt to 400-500 fps http://i.prntscr.com/OBcNBjxXSsGAz2Jegu3x3Q.png

**Comment by cout970** [comment]
I think we should close this, since the cause of the performance issues was the bug in #72
