### ISSUE TITLE
Suggestion: Be hable to hold down a button and receive multiple press events

### ISSUE THREAD

**Issue by cout970** [LiquidEngine/legui#67]
Basically MouseClickAction in MouseClickEvent has PRESS, CLICK and RELEASE, It would be cool to have REPEAT, this way you can hold down the a button to make it keep going and you don't have to spam click.

**Comment by ShchAlexander** [comment]
Can you please specify use case for this feature?
And also how do you think how often should be generated such events?

**Comment by cout970** [comment]
For example in my app, I have a '+' and '-' buttons to control a variable,  and I can only detect when you start or end pressing the mouse button to update the variable. 
I was thinking in something like the KeyEvent that has an option REPEAT and it's called several times per second, I'm not sure how long it takes to generare a new event (maybe it has something to do with the FPS?) I'm not sure exactly how that works

**Comment by ShchAlexander** [comment]
I'll take a look what I can do with this. Probably the best way is to generate own (REPEAT) event for mouse.
There is no such event in GLFW (probably cause no one system generates it).

**Comment by ShchAlexander** [comment]
The easiest way to implement this feature is to post post newly created mouse event with action REPEAT and create another listener. But in this case there will be one more subsystem which should be injected in `update` method of gameloop, which would be called as much as you need.
This subsystem also could be used to generate another events which could be used for example to update gui states (if gui elements are moving on screen, mouse is static and they should interact).

**Comment by ShchAlexander** [comment]
As discussed such thing could be using existing events and event listeners as additional event listener.
Event listener starts new thread which checks state of button in fixed time-step and if state of button is still pressed it generates new mouse click event which should be handled by same listener. (or just while loop).
