### ISSUE TITLE
Implement CSS

### ISSUE THREAD

**Issue by VadimGush** [LiquidEngine/legui#77]
Implement CSS with properties:
```

- border: <width> <style> <color>
- border-color: <color>
- border-width: <width>
- border-style: <style> // only solid for beggining is fine
- border-radius: <radius>
- background-color: <color>
- font-family: <family>
- opacity: <0-1>
- margin: <margin>
- width: <width>
- height: <height>
- min-width: <width>
- max-width: <width>
- min-height: <height>
- max-height: <height>
```

**Comment by orange451** [comment]
Having the ability to stylize with css would make this THE best java solution for ui components in java.

**Comment by ShchAlexander** [comment]
Nice to hear it!
I'll try to implement it little bit later (after some layouts).

**Comment by ShchAlexander** [comment]
Styles added to component system. This issue will be closed. New styles should be requested in separate tickets in next way: ticket per style.
