### ISSUE TITLE
Default demos run downscaled on retina mac

### ISSUE THREAD

**Issue by orange451** [LiquidEngine/legui#79]
This is what the default demos look like when running on my retina Macbook.
![image](https://user-images.githubusercontent.com/5247778/35362588-eec30f66-0133-11e8-9f20-5e1f6f03bae6.png)

First thing I tried was to mess around with the viewport. I found that replacing the viewport dimensions from the window size to the framebuffer size works perfectly:

> //Vector2i windowSize = context.getWindowSize();
> Vector2f windowSize = context.getFramebufferSize();
> glViewport(0, 0, (int)windowSize.x, (int)windowSize.y);

![image](https://user-images.githubusercontent.com/5247778/35362760-b16f07b8-0134-11e8-9b3b-39973233551b.png)

I haven't had any time to test if it still works on a non-retina screen.

**Comment by ShchAlexander** [comment]
I'll take a look at this as soon as possible.
Thank you for your report!

**Comment by ShchAlexander** [comment]
Fixed. Added demos to main project.
