### ISSUE TITLE
Add FlexBox Layout

### ISSUE THREAD

**Issue by cout970** [LiquidEngine/legui#82]
FlexBox is one of the CSS 3 layouts made by W3C: https://www.w3schools.com/css/css3_flexbox.asp in the link you can find examples and documentation of the layout.

It allows to arrange elements in columns and rows, allowing to specify the vertical and horizontal orientation of the elements (start, center, end) and adapting to the avaliable space making it easier to create responsive user interfaces.

**Comment by ShchAlexander** [comment]
Done
