### ISSUE TITLE
JVM crash in NvgRenderUtils.calculateTextBoundsRect

### ISSUE THREAD

**Issue by cout970** [LiquidEngine/legui#89]
I noticed that in the last version of develop (1.4.5-185) displaying a textarea causes a JVM crash, this is the log: https://gist.github.com/cout970/94e2c4496ced0cfc10c5dedbd43864a0

Basically the log says that NanoVG.nnvgTextBounds is trying to read data from 0x0 (NullPointerException), the stacktrace indicates that the last method called was `org.liquidengine.legui.system.renderer.nvg.util.NvgRenderUtils.calculateTextBoundsRect`

I checked my TextAreas to see if I was using a null string or something weird as inputs, but it was all normal.

**Comment by ShchAlexander** [comment]
I investigated and found root cause of this issue. The problem is that `nvgTextBounds` does not work with empty strings... I'll add some fix to avoid such exception in next develop build. But probably I need to reimplement whole text area rendering process....

**Comment by ShchAlexander** [comment]
Workaround published under `1.4.5-186` develop build.
