### ISSUE TITLE
Exclude any shapshot dependencies from release versions

### ISSUE THREAD

**Issue by nimelord** [LiquidEngine/legui#92]
I was trying to use release 1.3.3 and it made me bind "snapshot repositories":
Could not resolve dependencies for project com.blabla:test:jar:1.0-SNAPSHOT: Could not find artifact org.liquidengine:leutil:jar:0.0.3-SNAPSHOT in legui-releases (https://raw.github.com/LiquidEngine/repo/releases)

With "https://raw.github.com/LiquidEngine/repo/snapshots" it works, but I think it is not correct state of  dependencies.

**Comment by ShchAlexander** [comment]
Agree with you... This is not correct and I'll fix it...
