### ISSUE TITLE
Paste text in TextInput

### ISSUE THREAD

**Issue by cout970** [LiquidEngine/legui#95]
When the text of a TextInput is selected and the use tries to paste something (CTRL + V), instead of replacing the selected text, the pasted text gets appended at the end of the selection. 

Before paste:
![Before paste](https://user-images.githubusercontent.com/4961713/43402755-bdeaffde-9413-11e8-91eb-02725e10ea7e.png)

After paste:
![After paste](https://user-images.githubusercontent.com/4961713/43402778-c83d3394-9413-11e8-8396-8c54cabedc38.png)

The expected result was replacing the selected text with the content of the clipboard.

**Comment by ShchAlexander** [comment]
Hello @cout970, which version do you use?

**Comment by ShchAlexander** [comment]
This issue already fixed in lates develop build
