### ISSUE TITLE
SingleClassExample - Demos dont work under Ubuntu

### ISSUE THREAD

**Issue by SplotyCode** [LiquidEngine/legui#96]
MultipleWindowsNanoVG:
`Exception in thread "main" java.lang.NullPointerException
	at org.lwjgl.system.Checks.check(Checks.java:100)
	at org.lwjgl.nanovg.NanoVG.nvgBeginFrame(NanoVG.java:299)
	at org.liquidengine.legui.demo.MultipleWindowsNanoVG.main(MultipleWindowsNanoVG.java:108)
Shader shader/vert error:
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Shader shader/vert error:
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Shader shader/vert error:
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES`

MultipleWindowsMultipleThreadsExample and MultipleWindowsExample coused a 20 seconds lag were i cout not move the mouse when i pressed tab the program closed itself but the launcher was black after a few seconds it was all normal this happended 3 or 4 times. Strangley i can not reproduce it now. The consoled showed somethink red with "INTEL_X_LOCK" i dont know what the X was but it had to do somethink with input.

**Comment by ShchAlexander** [comment]
Hello @SplotyCode, Can you please specify your driver version and OpenGL info?
As I can see from shader/vert error you have no support of GLSL 1.50.... 
Are you using laptop with mobile graphic card?

**Comment by ShchAlexander** [comment]
Fixed issue with MultipleWindowsNanoVG demo.
